### ISSUE TITLE
Power/storms scripts should take filepaths as arguments

### ISSUE THREAD

**Issue by thomas-fred** [nismod/open-gira#103]
File location logic is encoded in the snakemake rules for the power/storms workflow, this allows snakemake to assemble the DAG and check where prior work can be reused. However, the majority of scripts in the power/storms workflow make similar assumptions about file paths. This means the file naming/location schemes are implemented twice. There is frequently workflow-type logic within the scripts.

This is not fully utilising the power of snakemake, is not DRY and makes it difficult to infer what the workflow is doing without reading scripts in detail.

I suggest that scripts should be modified to take the snakemake rule inputs as arguments and operate only using these paths.

**Comment by tomalrussell** [comment]
Some progress from #117, at least in preprocessing steps

**Comment by thomas-fred** [comment]
Getting there after #123. Once we have damages reworked, close this issue?
