### ISSUE TITLE
wget not specified as a requirementt

### ISSUE THREAD

**Issue by itrcrisks** [nismod/open-gira#143]
The environment.yml file does not specify to install wget, which is required.
Got error when running snakemake workflow

snakemake --cores 1 -- results/jamaica-latest_filter-road/edges.geoparquet

**Comment by thomas-fred** [comment]
This should now be fixed. Try pulling `main` for the new commit, reinstall the environment with `micromamba create -f environment.yml -y` and try your job again.

Let me know if it doesn't work.
