### ISSUE TITLE
How to get the SSP IRIS Storm data?

### ISSUE THREAD

**Issue by jacobbieker** [nismod/open-gira#185]
Hi,

Really great and interesting work! I was wondering how to get the IRIS data for the different SSPs, as mentioned on the website? I've gotten the ones from the Nature paper, but I don't see the SSPs in there?

**Comment by tomalrussell** [comment]
Hi @jacobbieker - thanks! You should contact Nathan Sparks and Ralf Toumi at Imperial directly (Nathan is corresponding author on that [paper](https://doi.org/10.1038/s41597-024-03250-y) and Ralf has contact details on his [webpage](http://www.sp.ph.ic.ac.uk/~rtoumi/)). Nathan prepared the return period maps for us while their paper was still in preprint.
