### ISSUE TITLE
Submit repository to snakemake catalogue

### ISSUE THREAD

**Issue by tomalrussell** [nismod/open-gira#24]
See https://snakemake.github.io/snakemake-workflow-catalog/?rules=true

 This catalog includes workflows based on the following criteria:

- [x] The workflow is contained in a public Github repository.
- [x] The repository has a readme, containing the words "snakemake" and "workflow" (case insensitive).
- [x] The repository contains a workflow definition named either Snakefile or workflow/Snakefile.
- [x] If the repository contains a folder rules or workflow/rules that folder must at least contain one file ending on .smk.
- [x] The repository is small enough to be cloned into a Github actions job (very large files should be handled via Git LFS, so that they can be stripped out during cloning).
- [x] The repository is not blacklisted [here](https://github.com/snakemake/snakemake-workflow-catalog/blob/main/blacklist.txt).

Standardized usage

In order to additionally appear in the "standardized usage" area, repositories additionally have to

- [x] have their main workflow definition named workflow/Snakefile (unlike for plain inclusion (see above), which also allows just Snakefile in the root of the repository),
- [x] provide configuration instructions under config/README.md,
- [x] contain a YAML file .snakemake-workflow-catalog.yml in their root directory, which configures the usage instructions displayed by this workflow catalog.

```
    usage:
      mandatory-flags: # optional definition of additional flags
        desc: # describe your flags here in a few sentences (they will be inserted below the example commands)
        flags: # put your flags here
      software-stack-deployment: # definition of software deployment method (at least one of conda, singularity, or singularity+conda)
        conda: true # whether pipeline works with --use-conda
        singularity: true # whether pipeline works with --use-singularity
        singularity+conda: true # whether pipeline works with --use-singularity --use-conda
      report: true # add this to confirm that the workflow allows to use 'snakemake --report report.zip' to generate a report containing all results and explanations
```

**Comment by tlestang** [comment]
I just added the YAML file. I'm not sure what the "flags" are, but looking at other examples in the catalog, this seems optional.

**Comment by tlestang** [comment]
I think the catalog is updated once a day

**Comment by tomalrussell** [comment]
TODO - check and contact
