### ISSUE TITLE
Process to network graph representation for roads

### ISSUE THREAD

**Issue by tomalrussell** [nismod/open-gira#35]
We import OSM data for highways, which comes defined as a set of nodes and a set of ways. A way's geometry is defined by a list of nodes and can be interpreted as a LineString. For routing over the highway network, we need to interpret this as a network graph, which can be defined as a set of edges corresponding to segments of highway (either all or part of a way) and nodes corresponding to highway junctions and endpoints (some of the OSM nodes are nodes in this sense, others just go into defining the edge segment geometry).

Aside: There are other representations specialised for fast response to A-B routing queries which provide a series of directions (turn left at the end of the road, third exit on the roundabout), particularly the [edge-expanded graph representation](https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation) used in OSRM. I don't think we want these, as our routing queries will mostly be bulk source-to-multiple-target in the context of transport simulation modelling, and the physical edges are the things that would be disrupted by flooding or other hazards.

Detail note: When creating box extracts from OSM data, the osmium tool provides a couple of ways of dealing with ways which extend beyond the boundaries of the box (https://osmcode.org/osmium-tool/manual.html#extract-strategies) and defaults to "complete ways", which includes all of a long road section in an extract if any part of it is within the box. We should handle roads which cross a box boundary by adding a node on the boundary, and leaving the part outside of the box to be handled inside of the box it belongs to.

Done looks like: each OSM highway extract box can be processed into a graph representation, stored in two parquet files: nodes and edges, where each maintains the source OSM ID and attributes, but nodes only includes junctions and endpoints, and edges may have been split into multiple segments at junctions.

**Comment by mjaquiery** [comment]
How:
* Make a list of all of the `node` references in an OSM slice
* Drop unique `node` references
* Convert each `way` into a .geopartquet row with:
  * For each segment (start node -> shared node; shared node -> shared node; ... x # ; shared node -> end node)
    * Linestring
    * (segment) Start node
      * Reference
      * Latitude
      * Longitude
      * Shared degree
    * (segment) End node
      * Reference
      * Latitude
      * Longitude
      * Shared degree
    * id (of overall `way`)
    * ... for other `way` columns defined in `config.yaml`
    * segment id (float: `id.segement_id`)
