### ISSUE TITLE
Factor out Holland wind field model to library

### ISSUE THREAD

**Issue by tomalrussell** [nismod/open-gira#78]
The wind field model used in cyclone wind speed estimation is small but dense and reusable enough to pull out and document and test.

See current implementation at https://github.com/nismod/open-gira/blob/8539447635fb2a5b50ecb21e55d9387616ae7a94/workflow/scripts/intersect/intersect_3_wind_extracter.py#L76-L93

Note that it (almost) follows the formulation from Lin and Chavas (2012, [pdf](https://www.sbafla.com/method/portals/methodology/FloodJournalArticles/Lin_Chavas_JGR12_ParametricWind.pdf)) section 3.2, based on Holland (1980, [doi](https://doi.org/10.1175/1520-0493(1980)108%3C1212:AAMOTW%3E2.0.CO;2)).

Environmental pressure values (standard estimate of background pressure away from the cyclone) are taken from the AIR hurricane model, Butke (2012, [blog](https://www.air-worldwide.com/publications/air-currents/2012/the-pressures-on-increased-realism-in-tropical-cyclone-wind-speeds-through-attention-to-environmental-pressure/)) Table 3.

https://github.com/nismod/open-gira/blob/39ba0b20e22cdf3cc60f3caffa11df5c3810a256/workflow/scripts/intersect/intersect_3_wind_extracter.py#L117-L119

**Comment by tomalrussell** [comment]
Existing implementations
- [tcrm](http://geoscienceaustralia.github.io/tcrm/docs/wind.html) by Geoscience Australia ([wind model code](https://github.com/GeoscienceAustralia/tcrm/blob/a9be18fe3d0cdc04fb6646703147edee20fcb094/wind/windmodels.py)) - clean implementation of multiple models, bundled in a larger library for tropical cyclone risk modelling, not published to pypi or conda.
- [climada](https://climada-python.readthedocs.io/en/stable/tutorial/climada_hazard_TropCyclone.html) by Weather and Climate Risks group at ETH Zurich ([wind model code](https://github.com/CLIMADA-project/climada_python/blob/1b1fb2d343a4721cf916080a017965d85522b273/climada/hazard/trop_cyclone.py)) - again bundled into a much larger framework for climate risk assessment, makes additional assumptions, would need a bit of figuring out how to calculate max wind speed experienced at exposure locations.

**Comment by tomalrussell** [comment]
[notebook.zip](https://github.com/nismod/open-gira/files/9423875/notebook.zip) with exploration around the model

**Comment by thomas-fred** [comment]
Closed with #123
