### ISSUE TITLE
Investigate weird data in power/storms target identification

### ISSUE THREAD

**Issue by thomas-fred** [nismod/open-gira#90]
Dubious data in `results/power_processed/all_boxes/<box>/targets_box_<box>.gpkg`:
- `area_km2` with negative values
- `population_density_at_centroid` all NoneType

**Comment by tomalrussell** [comment]
Looking briefly at a few area_km2 values, the absolute value looks correct, just negative. The areas are calculated using `pyproj.Geod` `geometry_area_perimeter` which gives a signed area (positive for counter-clockwise coordinates), and the polygons are coming from `GDALPolygonize` via `rasterio`, so I assume that's just throwing out some clockwise-ordered geometries and we should take `abs(area)`.

**Comment by tomalrussell** [comment]
Should look again after #117 changes - now in `results/processed/power/<box>/targets_<box>.parquet`

**Comment by thomas-fred** [comment]
No longer current
